sudo: true
language: python
python: '2.7'
env:
  global:
  - secure: d3th6YKbwX4B8mbYknA0knMWO27bLU1GGeJtFGcH+GdxYgxxzk1kxg27HQoqDhpJJiOMthruwikpThqbb7OSSe9+Fbi2jQpleWTwBta2vhy46FFA3zygv+RGBLw4QrxvAqUnFjsUDWrBlXknZj+D8Wnx71lwfj4lwZzTyON70+BbWtEwzPkNgELd2mq10LtGEiXF0hyVYHViqILvuqy7CkM1fQCsW5cfBBhl4xAph1KJebkEXo2dV29woDQ/0m26ubwdSqyoCk/KX0NPXm2KRvUHYGFISziNbzYPqAkl/jx/R/MLIqaUunC1FfccmrkqsM+NC3S4uOHjP/TPtNNuRlh59Cm7GQtfG+xA29sKp3ckdwHuKoRd2UDuGSZuhZtm4t2dju6//gLPhfXEX2MWWggL57GeP+emCJ1saAFrnJvzBlzTHnNASTI05fS5GXbOBeG/YM5OBD9ekzbelMEc+jTELdui54vQ5qLwjSAJNYs62uJ2xnXqSDrouDiB7dZ7/XhDZHvDXeHf2BDX4B7Om7a/PC+pinsWev0jjFPDPfKspqxGHCsEOoahfcngCecs8QdPQPbTnVOTkSpxnpdYhep+OPru4kzo7h7iNE7HHRDcq1IqV8M6cqptvZndS7TYIxISMjWmR/8H5oEoigV8P0y3usVVXUDTLswxl8noJao=
  - secure: 3QYql4pkhfVXIamDUWFlbTwOAM0T9TRwy289MfgpHWmgYJYq+H48TAY2IQEpbwgjW8CLjF04Th4bNV2SWp7pMEq5Z4jdmdJy4qeOJI2vuNWakVFg7atiiKDwVwI/3ubZCojReS6Qmj8blg6GpBu198Pd6XYS32MRu6wFSCL0nvvGTnE7PjZw+iSEGbykK8FaIEsi+VpNNw6KquKGCbiU4gIE5V5PT+K+p7GlBun/bZwA23DkpPyD+Eypk5kHhQ3skS/rnKKX8cI07n1kPA/ScMV9u/4S49fknYRhpe/Lf65U1COwIziGLCcWNuKR6gac76odjWGfgyUAOZVOMWp4DaL0xza9kZ6UPJnNwuA4RSx4USGRfL9QBi9P6IGc62AIY+fuf82aYF4wbxsIXqrG1MFjSt6BxBjLT71F5FkeWVqZmymQFhpFz8ndWrIZSrEQceIPWGCYi1HDyS27o75jNEwMcPf8uafJwK6c4fEK2/E8nTb0kY7QEPSmMGcpivqBO+9Ksue4eahvEk+Yu3a/U/WQq4bB0n1Hmg+6DaAohvP46QZ5MKpqBhiU2ATBvxa60873XgeH+qtFr//3fX0zFp8errsiGt7w4UU49DEdbSd6Z0U0UoFg43b94/1abA5BMoR9V0bnjoGlgVBVgBA+pMzE+2BC6BbU1iS47bVDoQs=
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build
after_success:
- sudo apt-get install ncftp
- ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD ftp.onstatic-pt.setupdns.net docs site/*
