sudo: true
language: python
python: '2.7'
env:
  global:
    - secure: "jTqcmqrIDKkGwX2KAuM+Wufc+p/xTskxINrfpTAvzAcpuAT7HulQ3flAgZW4mOJ3qLgjTpdyQ/b4LSYdkYVtDD+fwqoL/kH70BYznJIPwbJz/LIUi3T1nQT04VxkdjuqLVdmbN7DR1oyxuV1NNK4AB3p9SZgOLOC0nmZC8csIUo2roP6UrhDwlQwgfAvzWRRk8cFEU9YD3gmDVrSQ0z5p6grwN0paLFFnq5VaSrhzrBE/6oMynfmUaMMqs/U/m2/guIakeBvHRfOenKb52zTihipTlo1Ms9VIjM5hkCcIypNTt3WuHg9Yq/bsM/tMax9+vzbhpwcdRmYx+vl17yd5KsmihGmbp2+cDMeOpahnRCcPmXUoMTUq4TmCjt8GVfTmoYUFxu0PBXC/JOlPvsFdDcoGig8DX5ZJZNyvy9DUe0nnR0D5FWrETaYnTyGwU6gujniUp/WQaVwCZsZNTTfuuoNRFkaeABv0vir1D2Wb9Yn4ukuIMMO5MrYBs7efZER3T7n0bZcJCM9p3uI/W7UgyYkFjAsm8fd5CXlUD9/BbmNkZGafeKn0sl5wTALM7fWCgEwWE3eE+B8/F/oGq4qnrXMnVDzSspBS83IthXAbGUIxuSY7wJFhOpD/4flbvo8earroncwZASY/IYhmF3Ssj96M9DS+4+DfBuq5//i3qI="
    - secure: "CWXGmOi8drLVpA0DJi1d93iANtN7w4cRCm7YNbdlS5t7V6445doYU+oiI7u9MpStAr1/n5xwrPb4EpPNXY5eebwM9kVFFSDYJfAqLY3a3T1J/IwginZy8lkzfAfzKncFBNQ2rxozwoG95NIig45gNzVEQQOmtMZDGPGNktgPfPnTQsxpwzgmAlCjSlyoqdxvrH41yz5FY4ZCGhJT9U+lRCaTRXopHm4Q7wxihfgmeip6bVcUuxCp01Nu5z8bNzmOw6xZtRP9hvX2HjB2Q91ffkidwqbhv55xerJkivWJdZGcuqa1PcV04HYPgRaWZjT35mE5oxvHMqOl88jiJX/RHZAEadv+MkGzFfShe6kIPh3ljOYRK8W/OggXNBp+SqsbmME4rRAGvfTmfxAeDd9GjNhzkoHtboPE8m8oC7swLhGKb0n58U0mQ7ZM0X5zIrTSrbDCS8SrnlijIRjuzRFtyZInHtWc6Zk6b0/htckqWs3gUYpUoaCq3MrwVfDzi52XziYuE1Wr8tktMoqukh67mKUT8IeUbH8dWQc6irpYoot/TghQZ2sKtboEWkyeTwkNEj8Eddj4HoW4TYOgbuF/yIJtef+hlAn0yLccNr4RvG6WqAOyNLF0h3DuDsP/3QqO3IkVO0gwyFFQKmvq21jpKybmr8ULLbsKEqapxPKZGHM="
install:
  - pip install mkdocs
  - pip install mkdocs-bootswatch
script:
  - mkdocs build
after_success:
  - sudo apt-get install ncftp
  - ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD lhcp1023.webapps.net docs site/*
