## PAGE INDEX ##

pages:
- Home: index.md

- Frontend:
  - 'Part I - Frontend bases': 'frontend/1-bases.md'
  - 'Part II - Frontend +': 'frontend/2-plus.md'
  - 'Part III - Website generation': 'frontend/3-static.md'
  - 'Part IV - Javascript frameworks': 'frontend/4-js.md'

- Backend:
  - 'Part I - Ruby on Rails': 'backend/1-ror.md'
  - 'Part II - ASP.NET MVC': 'backend/2-aspnet-mvc.md'
  - 'Part III - Meteor': 'backend/3-meteor.md'

- Mobile:
  - 'Part I - Hybrid': 'mobile/1-hybrid.md'

- Databases:
  - '(*)Part I - Postgresql & Mysql': 'databases/1-rdbms.md'
  - 'Part II - Elasticsearch': 'databases/2-elastic.md'

- APIs and Webservices:
  - '(*)Part I - REST': 'apis/1-rest.md'
  - '(*)Part II - WCF': 'apis/2-wcf.md'

- Devops:
  - 'Part I - Virtual machines': 'devops/1-vms.md'
  - 'Part II - Docker': 'devops/2-docker.md'
  - '(*)Part III - CI': 'devops/3-ci.md'
  - '(*)Part IV - AWS': 'devops/4-aws.md'

- Agile:
  - 'Part I - Agile manifesto': 'agile/1-manifest.md'

- Trends:
  - '(*)Part I - Big Data & Analytics': 'trend/1-big-data.md'
  - '(*)Part II - IoT': 'trend/2-iot.md'



## CONFIGS ##

site_name: qb-docs
site_description: Become a great developer for free, learn the best tools from the best resources available online
site_author: tostasqb
repo_url: https://github.com/tostasqb/qb-docs
google_analytics: ['UA-75996053-1', 'tostasqb.com']

extra_css: ['extra-styles.css']
extra_javascript: [
  'hotjar.js'
]

markdown_extensions:
  - admonition

theme: material
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  version: '0.8'
  logo: 'img/tostas.png'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
