site_name: qb-docs
site_description: Become a web developer for free, learn from the best resources available online
site_author: tostasqb

repo_url: https://github.com/tostasqb/qb-docs
google_analytics: ['UA-75996053-1', 'tostasqb.com']
extra_css: ['extra-styles.css']

pages:
- Home: index.md
- Web Develpment:
  - 'Part I - Frontend bases': 'web-development/chapter-01.md'
  - 'Part II - Frontend +': 'web-development/chapter-02.md'
  - 'Part III - Website generation': 'web-development/chapter-03.md'
  - 'Part IV - Javascript in detail': 'web-development/chapter-04.md'
  - 'Part IV - Backend': 'web-development/chapter-05.md'

theme: flatly
