site_name: qb-docs
site_description: Become a great developer for free, learn the best tools from the best resources available online
site_author: tostasqb

repo_url: https://github.com/tostasqb/qb-docs
google_analytics: ['UA-75996053-1', 'tostasqb.com']
extra_css: ['extra-styles.css']
extra_javascript: ['hotjar.js']

theme: material
extra:
  version: '0.6.0'
  logo: 'img/tostas.png'

# dev_addr: 'http://127.0.0.1:8000/docs'

pages:
- Home: index.md

- Frontend:
  - 'Part I - Frontend bases': 'frontend/chapter-01.md'
  - 'Part II - Frontend +': 'frontend/chapter-02.md'
  - 'Part III - Website generation': 'frontend/chapter-03.md'
  - 'Part IV - Javascript frameworks': 'frontend/chapter-04.md'
  - '(*)Part V - Meteor': 'frontend/chapter-05.md'

- Backend:
  - 'Part I - Ruby on Rails': 'backend/chapter-01.md'
  - 'Part II - ASP.NET MVC': 'backend/chapter-02.md'

- Mobile:
  - 'Part I - Hybrid': 'mobile/chapter-01.md'

- Databases:
  - '(*)Part I - Postgresql & Mysql': 'databases/chapter-01.md'
  - 'Part II - Elasticsearch': 'databases/chapter-02.md'

- APIs and Webservices:
  - '(*)Part I - REST': 'apis/chapter-01.md'
  - '(*)Part II - WCF': 'apis/chapter-02.md'

- Devops:
  - 'Part I - Virtual machines': 'devops/chapter-01.md'
  - 'Part II - Containers': 'devops/chapter-02.md'
  - '(*)Part III - Deploy': 'devops/chapter-03.md'

- Agile:
  - 'Part I - Agile manifesto': 'agile/chapter-01.md'

- Trends:
  - '(*)Part I - Big Data & Analytics': 'trend/chapter-01.md'
  - '(*)Part II - AWS': 'trend/chapter-02.md'
